name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core:
  cloud_firestore: ^4.3.1
  connectivity_plus:
  file_picker: ^5.3.2
  http:
  firebase_storage: ^11.2.3
  firebase_database: ^10.2.3
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

